// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDv80rm5zl6MOyV0I6v79obWbXbUTyUJj0',
    appId: '1:671089022052:web:403f8f56a9de5e60bdfb71',
    messagingSenderId: '671089022052',
    projectId: 'qrtest-b23bd',
    authDomain: 'qrtest-b23bd.firebaseapp.com',
    storageBucket: 'qrtest-b23bd.appspot.com',
    measurementId: 'G-Z24DNWDLPW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkJY5H82bWKKzF4kcF-_huInNI6g3l_lY',
    appId: '1:671089022052:android:6248619f321e118ebdfb71',
    messagingSenderId: '671089022052',
    projectId: 'qrtest-b23bd',
    storageBucket: 'qrtest-b23bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyvTFPJdGXG-PGKHWLr7GUomyiaW0jau4',
    appId: '1:671089022052:ios:91e38986588c359cbdfb71',
    messagingSenderId: '671089022052',
    projectId: 'qrtest-b23bd',
    storageBucket: 'qrtest-b23bd.appspot.com',
    iosClientId: '671089022052-us4r8j5bjdmvn7hh2ppq57omigmshmpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrscanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyvTFPJdGXG-PGKHWLr7GUomyiaW0jau4',
    appId: '1:671089022052:ios:91e38986588c359cbdfb71',
    messagingSenderId: '671089022052',
    projectId: 'qrtest-b23bd',
    storageBucket: 'qrtest-b23bd.appspot.com',
    iosClientId: '671089022052-us4r8j5bjdmvn7hh2ppq57omigmshmpm.apps.googleusercontent.com',
    iosBundleId: 'com.example.qrscanner',
  );
}
